apiVersion: v1
kind: Service
metadata:
  name: scraper
  namespace: default
spec: 
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    env: dev
    functionality: address
    name: scraper
  type: LoadBalancer