apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-04T14:02:47Z"
  labels:
    env: dev
    functionality: address
    name: scraper
  name: scraper
  namespace: default
spec: 
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    env: dev
    functionality: address
    name: scraper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}